// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2reKe1d9LDCTrYXhHTFrf5nBLiakKcGE',
    appId: '1:707715729232:web:7d427ec5fe34fcde104e55',
    messagingSenderId: '707715729232',
    projectId: 'note-it-master',
    authDomain: 'note-it-master.firebaseapp.com',
    storageBucket: 'note-it-master.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA80VUWsGY8t7VNF4d2pBwaIEUTdRn70A',
    appId: '1:707715729232:android:bde21e11eced564d104e55',
    messagingSenderId: '707715729232',
    projectId: 'note-it-master',
    storageBucket: 'note-it-master.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2reKe1d9LDCTrYXhHTFrf5nBLiakKcGE',
    appId: '1:707715729232:web:0c00b3324f42883a104e55',
    messagingSenderId: '707715729232',
    projectId: 'note-it-master',
    authDomain: 'note-it-master.firebaseapp.com',
    storageBucket: 'note-it-master.firebasestorage.app',
  );
}
